### ISSUE TITLE
Key derivation faulty?

### ISSUE THREAD

**Issue by benma** [roosmaa/go-monero#1]
Hi

https://github.com/roosmaa/go-monero/blob/e1d6aefb874bd9fd84cdd78ad37c41e1607295d5/crypto/crypto.go#L187

To derive a public key from a public key, you add the group elements. This does not ensure that the corresponding private key is valid. A valid ed25519 key has the first three bits set to zero and the last two bits set to 1 and 0. 

If you simply add the secret keys (https://github.com/roosmaa/go-monero/blob/e1d6aefb874bd9fd84cdd78ad37c41e1607295d5/crypto/crypto.go#L204), you don't ensure that the resulting key has that property.

Are you simply disregarding the fact that the private keys should have those 5 bits fixed, or am I missing something?

**Comment by roosmaa** [comment]
It's been a while since I wrote this code (and mind you I didn't actually finish implementing it all). But all of the crypto was a direct port from the C code (since I'm no crypto expert, I did not dare to change anything). If I remember correctly, then the code passed all of the crypto tests that Monero had. Maybe they've changed something recently?

The main point of this library was to have a way to communicate with the Monero daemon over both (JSON + binary) of the RPC interfaces. Basically everything needed to implement a custom wallet (which I was trying to do at the time). Since I left the crypto scene ~6 months ago, I haven't really done anything with this code. It would be nice if someone picked up where I left off, though. If you wish to do so, let me know and I'll point this repo to yours. :)

**Comment by benma** [comment]
Thanks for the offer, but I am not involved in Monero, so I am not the guy to lead this this project :)

Anyway, for posterity: in the meantime I figured out that the most significant bit (bit 254, little endian) is set to prevent timing attacks when using group point addition with a bad implementation of the montgomery ladder. You can implement a fixed time montgomery ladder, in which case setting the bit does not win you anything, but apparently, naive implementations suffer are not fixed time but depend on the position of the most significant bit. ed25519 specifies it as a preventive measure.

Reference: http://crypto.stackexchange.com/questions/11810/when-using-curve25519-why-does-the-private-key-always-have-a-fixed-bit-at-2254/11818
